from selenium import webdriver
b=webdriver.ChromeOptions()
b.add_experimental_option("detach",True)
a = webdriver.Chrome(options=b)
url="https://www.amazon.co.uk/"
a.get(url)
a.maximize_window()
a.minimize_window()
a.fullscreen_window()
z= a.find_element("id","sp-cc-accept")
z.click()
find_item=a.find_element("id","twotabsearchtextbox")
find_item.send_keys("kingdom")
clicksearch=a.find_element("id","nav-search-submit-button")
clicksearch.click()
# mp=a.find_element("class name", "nav-line-2")
# mp.click()
# login=a.find_element("class name","nav-action-inner")
# #login.click()
a.fullscreen_window()